### ISSUE TITLE
Bad-Request Error

### ISSUE THREAD

**Issue by ryan4volts** [issus/DigiKeyApi#1]
Preface: Thanks for uploading this, looks much better than the DigiKey git repo one! And I likely think this issue is just me, so reaching out as you may know what I am missing!

I am running MSVS 2019 with .NET Core v3.1

I downloaded your app and changed the target framework to v3.1 in all 3 projects (only one of them was originally targeting v6.1). After filling in the required 2 items in the apiclient.config taken from the Sandbox example. Click run and the request fails.
```
Unhandled exception. System.Net.Http.HttpRequestException: Request failed with status code BadRequest
   at RestSharp.RestClient.ThrowIfError(RestResponse response)
   at RestSharp.RestClientExtensions.PostAsync(RestClient client, RestRequest request, CancellationToken cancellationToken)
   at DigiKey.Api.OAuth2.OAuth2Helpers.RefreshTokenAsync() in C:\Users\MyUserName12\Documents\My_Projects\StockCount\DigiKeyApi-main\DigiKey.Api\OAuth2\OAuth2Helpers.cs:line 59
   at DigiKey.Api.ConsoleClient.Program.Main(String[] args) in C:\Users\MyUserName12\Documents\My_Projects\StockCount\DigiKeyApi-main\DigiKey.Api.ConsoleClient\Program.cs:line 23
   at DigiKey.Api.ConsoleClient.Program.<Main>(String[] args)
```

apiclient.config (with replacemets)
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <appSettings file="">
        <clear />
        <add key="ApiClient.ClientId" value="Ncgqt------------------------ljX" />
        <add key="ApiClient.ClientSecret" value="hTcL----------SZ" />
        <add key="ApiClient.RedirectUri" value="https://localhost:44301/Home/FinishAuth" />
        <add key="ApiClient.AccessToken" value="" />
        <add key="ApiClient.RefreshToken" value="" />
        <add key="ApiClient.ExpirationDateTime" value="" />
        <add key="ApiClient.BaseAddress" value="https://sandbox-api.digikey.com" />
		<!--<add key="ApiClient.BaseAddress" value="https://api.digikey.com" />-->
    </appSettings>
</configuration>
```
![image](https://user-images.githubusercontent.com/33822039/153114851-a5c5d59f-49d4-40a8-a79a-8df4344f91b5.png)

![image](https://user-images.githubusercontent.com/33822039/153114112-81880b38-c61e-4565-8288-815d4161fb32.png)

**Comment by issus** [comment]
It looks like you're trying to run the API call - but your config file doesn't have an access/refresh token which might be the problem?

Try running the OAuth2ConsoleClient project first this should take you to DigiKey's page to approve the login, then generate you a new config file. It will update the config file in the solution directory, but also show you the config file in your web browser. Once you have the access token in the config, I suspect it will work better!

**Comment by ryan4volts** [comment]
Yea I found 2 things out. The first and main issue was as you mentioned, there are 2 applications and I needed to run the OAuth one first.

The second is that I have no connections coming through when hosting a HttpListener server specially on `https://localhost:<AnyPort>` though `https://localhost` works fine and `http://localhost:<AnyPort>` works fine as well. I have been playing around with the `netsh http add urlacl url=https://+:8085/ user=everyone listen=yes` though it doesn't appear to change anything.
```
 Reserved URL            : https://+:8085/
        User: \Everyone
            Listen: Yes
            Delegate: No
            SDDL: D:(A;;GX;;;WD)
```
In code it comes out as:
```
httpListener.Prefixes.Add("https://localhost:8085/");
httpListener.Prefixes.Add("https://+:8085/");
```
I'll close this now though unless you could shed light on the above?

**Comment by issus** [comment]
The localhost server is only for the oauth callback. [OAuth2 ](https://oauth.net/2/) requires a URL to redirect to, which will contain the bearer token in the url. So it's only used during the creation of your credentials - the main API client code has no use for the redirect url so you wont see anything going to it at all. Likewise, only your local browser (the window which the oauth client created) will access that local server, nothing would come through remotely to it.
